inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AssignmentIndentation:
  IndentationWidth: 4
