language: ruby
sudo: required
rvm:
  - 2.3.1
before_install:
  - sh ./setup/install_mecab_travis.sh
install: bundle install --without development production --deployment
script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
services:
    - redis-server
