os: linux
dist: xenial
language: ruby
cache: bundler
rvm:
  - 2.6.4
before_install:
  - sudo apt-get -y install libidn11-dev
  - sh ./setup/install_mecab_travis.sh
install: bundle install --without development production --deployment
script:
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  - bundle exec rspec
services:
  - mysql
  - redis
