dist: xenial
language: ruby
cache: bundler
sudo: required
rvm:
  - 2.6.4
  - 2.7.0-preview3
before_install:
  - sh ./setup/install_mecab_travis.sh
install: bundle install --without development production --deployment
script:
  - bundle exec rake db:create db:schema:load
  - bundle exec rspec
services:
  - mysql
  - redis-server
