default: &default
  twitter_users:
    create_record_interval: <%= 1.hours %>
  twitter_db_users:
    update_record_interval: <%= 6.hours %>
  usage_stat_recently_created: <%= 30.minutes %>
  search_limitation:
    soft_limit: 2000
    hard_limit: 60000
  search_count_limitation:
    sign_in_bonus: 3
    sharing_bonus: 2
    anonymous: 2
    basic_plan: 10
  create_follow_limitation:
    anonymous: 2
    basic_plan: 100
  create_unfollow_limitation:
    anonymous: 2
    basic_plan: 20
  cluster_bad_words_path: 'data/cluster_bad_words.json'
  cluster_good_words_path: 'data/cluster_good_words.json'
  faq_path: 'data/faq.json'
development:
  <<: *default
  usage_stat_recently_created: <%= 1.minute %>
production:
  <<: *default
test:
  <<: *default
  cluster_bad_words_path: 'data/cluster_bad_words.test.json'
  cluster_good_words_path: 'data/cluster_good_words.test.json'
