development:
  twitter_api_cache_prefix: '%Y%m%d%H'
  twitter_user_recently_created_threshold: 1800
  background_search_log_recently_created_threshold: 300
  background_update_log_recently_created_threshold: 300
  result_cache_ttl: 43200
  many_friends_threshold: 1000
  too_many_friends_threshold: 5000
production:
  twitter_api_cache_prefix: '%Y%m%d%H'
  twitter_user_recently_created_threshold: 1800
  background_search_log_recently_created_threshold: 300
  background_update_log_recently_created_threshold: 300
  result_cache_ttl: 43200
  many_friends_threshold: 1000
  too_many_friends_threshold: 5000
