default: &default
  twitter_user_recently_created: 1800
  background_search_log_recently_created: 300
  background_update_log_recently_created: 300
  background_search_worker_recently_searched: 300
  page_cache_ttl: 86400
  many_friends_threshold: 1000
  too_many_friends_threshold: 5000
  bot_path: 'data/bot.json'
  cluster_bad_words_path: 'data/cluster_bad_words.json'
  cluster_good_words_path: 'data/cluster_good_words.json'
  faq_path: 'data/faq.json'
  kaomoji_path: 'data/kaomoji.json'
development:
  <<: *default
  twitter_user_recently_created: 120
  background_search_log_recently_created: 120
  background_update_log_recently_created: 120
  background_search_worker_recently_searched: 120
  page_cache_ttl: 120
production:
  <<: *default
test:
  <<: *default
  twitter_user_recently_created: 0
  bot_path: 'data/bot.test.json'
