default: &default
  twitter_users:
    create_record_interval: <%= 1.hour %>
  twitter_db_users:
    update_record_interval: <%= 6.hours %>
  search_requests:
    skip_duplicate_job_interval: <%= 1.minute %>
  usage_stat_recently_created: <%= 30.minutes %>
  search_limitation:
    soft_limit: 2000
    hard_limit: 30000
  search_count_limitation:
    sign_in_bonus: 3
    sharing_bonus: 2
    anonymous: 2
    basic_plan: 10
  anonymous_follow_requests_limit: 2
  basic_plan_follow_requests_limit: 100
  anonymous_unfollow_requests_limit: 2
  basic_plan_unfollow_requests_limit: 20
  cluster_bad_words_path: 'data/cluster_bad_words.json'
  cluster_good_words_path: 'data/cluster_good_words.json'
  faq_path: 'data/faq.json'
development:
  <<: *default
  twitter_users:
    create_record_interval: <%= 10.minutes %>
  usage_stat_recently_created: <%= 1.minute %>
production:
  <<: *default
test:
  <<: *default
  twitter_users:
    create_record_interval: <%= 1.minute %>
  search_requests:
    skip_duplicate_job_interval: <%= 1.minute - 1 %>
  cluster_bad_words_path: 'data/cluster_bad_words.test.json'
  cluster_good_words_path: 'data/cluster_good_words.test.json'
