default: &default
  twitter_user_recently_created: <%= 30.minutes %>
  log_recently_created: <%= 5.minutes %>
  background_search_log_recently_created: <%= 5.minutes %>
  background_update_log_recently_created: <%= 5.minutes %>
  recently_searched: <%= 5.minutes %>
  page_cache_ttl: <%= 3.days %>
  many_friends_threshold: 1000
  too_many_friends_threshold: 5000
  bot_path: 'data/bot.json'
  cluster_bad_words_path: 'data/cluster_bad_words.json'
  cluster_good_words_path: 'data/cluster_good_words.json'
  faq_path: 'data/faq.json'
  kaomoji_path: 'data/kaomoji.json'
development:
  <<: *default
  twitter_user_recently_created: <%= 1.minute %>
  log_recently_created: <%= 1.minute %>
  background_search_log_recently_created: <%= 1.minute %>
  background_update_log_recently_created: <%= 1.minute %>
  recently_searched: <%= 1.minute %>
  page_cache_ttl: <%= 1.minute %>
production:
  <<: *default
test:
  <<: *default
  twitter_user_recently_created: <%= 1.minute %>
  bot_path: 'data/bot.test.json'
