:concurrency: <%= require 'dotenv/load'; ENV.fetch("SIDEKIQ_PROMPT_REPORTS_CONCURRENCY") { 3 } %>
:timeout: 60
:pidfile: ./tmp/pids/sidekiq_prompt_reports.pid
:logfile: ./log/sidekiq_prompt_reports.log
:tag: sidekiq_prompt_reports
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - CreateTestReportWorker
  - ForceCreatePromptReportWorker
  - CreatePromptReportWorker
  - StartSendingPromptReportsWorker
