:concurrency: <%= require 'dotenv/load'; ENV.fetch("SIDEKIQ_IMPORT_CONCURRENCY") { 5 } %>
:timeout: 60
:pidfile: ./tmp/pids/sidekiq_import.pid
:logfile: ./log/sidekiq_import.log
:tag: sidekiq_import
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - ImportTwitterUserRelationsWorker
  - WriteToS3Worker
  - CreateTwitterDBUserWorker
