:concurrency: 3
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_all.pid
:logfile: ./log/sidekiq_all.log
:tag: sidekiq_all
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - logging
  - messaging
  - misc
  - CreatePromptReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterDBProfileWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - DeleteFromS3Worker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - ImportTwitterUserRelationsWorker
  - ResetTooManyRequestsWorker
  - StartSendingPromptReportsWorker
  - UpdateUsageStatWorker
  - WriteProfilesToS3Worker
  - WriteToS3Worker
