:concurrency: 1
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_unfollow.pid
:logfile: ./log/sidekiq_unfollow.log
:tag: sidekiq_unfollow
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - unfollow
