:concurrency: 20
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - egotter
  - CreateForbiddenUserWorker
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreateNotificationMessageWorker
  - CreatePageCacheLogWorker
  - CreatePageCacheWorker
  - CreatePromptReportWorker
  - CreateRelationshipWorker
  - CreateSearchHistoriesWorker
  - CreateSearchLogWorker
  - CreateSignInLogWorker
  - CreateTweetsWorker
  - CreateTwitterUserWorker
  - ForceUpdateTwitterUserWorker
  - ImportFriendsAndFollowersWorker
  - ImportInactiveFriendsAndInactiveFollowersWorker
  - ImportReplyingRepliedAndFavoritesWorker
  - UpdateNotificationMessageWorker
  - UpdateTwitterUserWorker
  - rollbar
