:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:tag: sidekiq_misc
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - logging
  - messaging
  - misc
  - DeleteFromS3Worker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker

  - ResetTooManyRequestsWorker
  - UpdateUsageStatWorker
  - WriteProfilesToS3Worker
  - WriteToS3Worker
  - rollbar
