:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:queues:
  - logging
  - CreateCacheWorker
  - CreateFollowWorker
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateTweetsWorker
  - CreateUnfollowWorker
  - CreateWelcomeMessageWorker
  - DeleteNotFoundUserWorker
  - DeleteForbiddenUserWorker
  - DeleteTweetsWorker
  - FollowEgotterWorker
  - ImportDynamodbFriendshipsWorker
  - ImportDynamodbFollowershipsWorker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - SendMetricsWorker
  - UpdateAudienceInsightWorker
  - UpdateAuthorizedWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchReportWorker
  - UpdateNewsReportWorker
  - UpdateWelcomeMessageWorker

  - CreateForbiddenUserWorker
  - CreateNotFoundUserWorker
  - RepairS3FriendshipsWorker
  - ResetTooManyRequestsWorker
  - TweetEgotterWorker
  - SetSearchCountWorker
  - UpdateSearchHistoriesWorker
  - UpdateUsageStatWorker
  - rollbar
