:concurrency: 3
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_all.pid
:logfile: ./log/sidekiq_all.log
:queues:
  - logging
  - misc
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - CreateWelcomeMessageWorker
  - DelayedCreateTwitterUserWorker
  - DelayedImportTwitterUserRelationsWorker
  - ImportDynamodbFriendshipsWorker
  - ImportDynamodbFollowershipsWorker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - ImportTwitterUserRelationsWorker
  - ResetTooManyRequestsWorker
  - UpdateAudienceInsightWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchHistoriesWorker
  - UpdateSearchReportWorker
  - UpdateUsageStatWorker
  - UpdateNewsReportWorker
  - UpdateWelcomeMessageWorker
