:concurrency: 3
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_all.pid
:logfile: ./log/sidekiq_all.log
:queues:
  - logging
  - messaging
  - misc
  - CreatePromptReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - DeleteFromS3Worker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - ImportTwitterUserRelationsWorker
  - ResetTooManyRequestsWorker
  - UpdateUsageStatWorker
  - WriteProfilesToS3Worker
  - WriteToS3Worker
