:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:queues:
  - CreateNotificationMessageWorker
  - CreatePageCacheWorker
  - CreatePromptReportWorker
  - CreateSearchReportWorker
  - CreateSearchHistoriesWorker
  - CreateTweetsWorker
  - SendMetricsWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchReportWorker

  - CreateForbiddenUserWorker
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreatePageCacheLogWorker
  - CreateCrawlerLogWorker
  - CreateSearchLogWorker
  - CreateSignInLogWorker
  - TweetEgotterWorker
  - UpdateSearchLogWorker
  - rollbar
