<% require 'dotenv/load' %>:concurrency: <%= ENV.fetch("SIDEKIQ_MISC_CONCURRENCY") { 5 } %>
:timeout: 600
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:tag:
  - sidekiq_misc
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - logging
  - messaging
  - misc
  - ResetTooManyRequestsWorker
  - UpdateUsageStatWorker
  - creating_low
  - deleting_low
  - deleting
  - follow
  - unfollow
  - rollbar
