:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:tag: sidekiq_misc
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - deleting_high
  - logging
  - messaging
  - misc
  - ResetTooManyRequestsWorker
  - UpdateUsageStatWorker
  - WriteToS3Worker
  - deleting
  - DetectFailureWorker
  - rollbar
