:concurrency: 2
:timeout: 10
:pidfile: ./tmp/pids/sidekiq2.pid
:logfile: ./log/sidekiq2.log
:queues:
  - egotter
  - CreateRelationshipWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterUserWorker
  - ForceUpdateTwitterUserWorker
  - UpdateTwitterUserWorker
