:concurrency: 20
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - egotter
  - CreateNotificationMessageWorker
  - CreatePageCacheWorker
  - CreatePromptReportWorker
  - CreateRelationshipWorker
  - CreateSearchHistoriesWorker
  - CreateTweetsWorker
  - CreateTwitterUserWorker
  - ForceUpdateTwitterUserWorker
  - UpdateNotificationMessageWorker
  - UpdateTwitterUserWorker
