:concurrency: 2
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_import.pid
:logfile: ./log/sidekiq_import.log
:queues:
  - ImportFriendsAndFollowersWorker
  - ImportFriendshipsAndFollowershipsWorker
  - ImportInactiveFriendsAndInactiveFollowersWorker
  - ImportReplyingRepliedAndFavoritesWorker
  - ImportTwitterUserRelationsWorker
