:concurrency: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - egotter
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreateNotificationMessageWorker
  - CreatePageCacheLogWorker
  - CreatePageCacheWorker
  - CreatePromptReportWorker
  - CreateRelationshipWorker
  - CreateSearchLogWorker
  - CreateSignInLogWorker
  - CreateTwitterUserWorker
  - FollowEgotterWorker
  - UpdateNotificationMessageWorker
  - UpdateTwitterUserWorker
  - rollbar
