:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:queues:
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateSearchReportWorker
  - CreateTweetsWorker
  - SendMetricsWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchReportWorker
  - UpdateNewsReportWorker

  - CreateForbiddenUserWorker
  - CreateNotFoundUserWorker
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreateCrawlerLogWorker
  - CreateSearchLogWorker
  - CreateSignInLogWorker
  - TweetEgotterWorker
  - UpdateSearchHistoriesWorker
  - UpdateSearchLogWorker
  - UpdateUsageStatWorker
  - rollbar
