<% require 'dotenv/load' %>:concurrency: <%= ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 } %>
:timeout: 600
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:tag:
  - sidekiq
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - CreateSignedInTwitterUserWorker
  - CreateTwitterUserWorker
  - WriteToS3Worker
  - CreateTwitterDBUserWorker
