:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:tag: sidekiq
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - logging
  - messaging
  - misc
  - creating_low
  - CreateTestReportWorker
  - ForceCreatePromptReportWorker
  - CreatePromptReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - ImportTwitterUserRelationsWorker
  - ResetTooManyRequestsWorker
  - StartSendingPromptReportsWorker
  - WriteToS3Worker
  - deleting
  - follow
  - unfollow
  - rollbar
