<% require 'dotenv/load' %>:concurrency: 1
:timeout: 30
:pidfile: ./tmp/pids/sidekiq_follow.pid
:logfile: ./log/sidekiq_follow.log
:tag:
  - sidekiq_follow
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - follow
