:concurrency: 3
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_all.pid
:logfile: ./log/sidekiq_all.log
:queues:
  - logging
  - CreateCacheWorker
  - CreateFollowWorker
  - CreateForbiddenUserWorker
  - CreateNotFoundUserWorker
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTweetsWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - CreateUnfollowWorker
  - CreateWelcomeMessageWorker
  - DelayedCreateTwitterUserWorker
  - DelayedImportTwitterUserRelationsWorker
  - DeleteNotFoundUserWorker
  - DeleteForbiddenUserWorker
  - DeleteTweetsWorker
  - FollowEgotterWorker
  - ImportDynamodbFriendshipsWorker
  - ImportDynamodbFollowershipsWorker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - ImportFriendsAndFollowersWorker
  - ImportFriendshipsAndFollowershipsWorker
  - ImportInactiveFriendsAndInactiveFollowersWorker
  - ImportReplyingRepliedAndFavoritesWorker
  - ImportTwitterUserRelationsWorker
  - ImportUserWorker
  - RepairS3FriendshipsWorker
  - ResetTooManyRequestsWorker
  - TweetEgotterWorker
  - UpdateAudienceInsightWorker
  - UpdateAuthorizedWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchHistoriesWorker
  - UpdateSearchReportWorker
  - UpdateUsageStatWorker
  - UpdateNewsReportWorker
  - SetSearchCountWorker
  - UpdateWelcomeMessageWorker
