:concurrency: 1
:pidfile: ./tmp/pids/sidekiq_logging.pid
:logfile: ./log/sidekiq_logging.log
:queues:
  - CreateForbiddenUserWorker
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreatePageCacheLogWorker
  - CreateSearchLogWorker
  - CreateSignInLogWorker
  - rollbar
