:concurrency: <%= require 'dotenv/load'; ENV.fetch("SIDEKIQ_MISC_CONCURRENCY") { 5 } %>
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:tag: sidekiq_misc
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - logging
  - messaging
  - misc
  - UpdateAudienceInsightWorker
  - creating_low
  - ResetTooManyRequestsWorker
  - UpdateUsageStatWorker
  - deleting
  - DetectFailureWorker
  - rollbar
