:concurrency: 20
:pidfile: ./tmp/pids/sidekiq_import.pid
:logfile: ./log/sidekiq_import.log
:queues:
  - ImportFriendsAndFollowersWorker
  - ImportInactiveFriendsAndInactiveFollowersWorker
  - ImportReplyingRepliedAndFavoritesWorker
