<% require 'dotenv/load' %>:concurrency: <%= ENV.fetch("SIDEKIQ_IMPORT_CONCURRENCY") { 5 } %>
:timeout: 600
:pidfile: ./tmp/pids/sidekiq_import.pid
:logfile: ./log/sidekiq_import.log
:tag:
  - sidekiq_import
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - ImportTwitterUserRelationsWorker
  - WriteToS3Worker
  - CreateTwitterDBUserWorker
