:concurrency: <%= require 'dotenv/load'; ENV.fetch("SIDEKIQ_CONCURRENCY") { 5 } %>
:timeout: 60
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:tag: sidekiq
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - CreateSignedInTwitterUserWorker
  - CreateTwitterUserWorker
  - WriteToS3Worker
  - CreateTwitterDBUserWorker
