:concurrency: 2
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_import.pid
:logfile: ./log/sidekiq_import.log
:tag: sidekiq_import
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - ImportTwitterUserRelationsWorker
  - WriteToS3Worker
  - CreateTwitterDBUserWorker
