<% require 'dotenv/load' %>:concurrency: 1
:timeout: 60
:pidfile: ./tmp/pids/sidekiq_unfollow.pid
:logfile: ./log/sidekiq_unfollow.log
:tag:
  - sidekiq_unfollow
  - <%= ENV.fetch("AWS_NAME_TAG") { "NONAME" } %>
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - unfollow
