:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:queues:
  - logging
  - misc
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateWelcomeMessageWorker
  - ImportDynamodbFriendshipsWorker
  - ImportDynamodbFollowershipsWorker
  - ImportS3FriendshipsWorker
  - ImportS3FollowershipsWorker
  - ImportTwitterDbS3UsersWorker
  - UpdateAudienceInsightWorker
  - UpdateAuthorizedWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchReportWorker
  - UpdateNewsReportWorker
  - UpdateWelcomeMessageWorker

  - ResetTooManyRequestsWorker
  - UpdateSearchHistoriesWorker
  - UpdateUsageStatWorker
  - rollbar
