:concurrency: 3
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_all.pid
:logfile: ./log/sidekiq_all.log
:queues:
  - CreateCrawlerLogWorker
  - CreateForbiddenUserWorker
  - CreateNotFoundUserWorker
  - CreateModalOpenLogWorker
  - CreateNotificationMessageWorker
  - CreatePollingLogWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateRelationshipWorker
  - CreateSearchLogWorker
  - CreateSearchErrorLogWorker
  - CreateSignedInTwitterUserWorker
  - CreateSignInLogWorker
  - CreateTweetsWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - CreateWelcomeMessageWorker
  - DelayedCreateTwitterUserWorker
  - DelayedImportTwitterUserRelationsWorker
  - DeleteNotFoundUserWorker
  - DeleteForbiddenUserWorker
  - DeleteTweetsWorker
  - FollowEgotterWorker
  - ImportFriendsAndFollowersWorker
  - ImportFriendshipsAndFollowershipsWorker
  - ImportInactiveFriendsAndInactiveFollowersWorker
  - ImportReplyingRepliedAndFavoritesWorker
  - ImportTwitterUserRelationsWorker
  - ImportUserWorker
  - ResetTooManyRequestsWorker
  - TweetEgotterWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchHistoriesWorker
  - UpdateSearchLogWorker
  - UpdateSearchReportWorker
  - UpdateUsageStatWorker
  - UpdateNewsReportWorker
  - SetSearchCountWorker
  - UpdateWelcomeMessageWorker
