<% require 'dotenv/load' %>:concurrency: 5
:timeout: 5
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:tag:
  - sidekiq
:environment: <%= ENV.fetch("RAILS_ENV") { "development" } %>
:queues:
  - creating_high
  - deleting_high
  - logging
  - messaging
  - misc
  - creating_low
  - deleting_low
  - CreateTestReportWorker
  - ForceCreatePromptReportWorker
  - CreatePeriodicReportWorker
  - CreatePromptReportWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterDBUserWorker
  - CreateTwitterUserWorker
  - CreateBatchTwitterUserWorker
  - ImportTwitterUserRelationsWorker
  - ResetTooManyRequestsWorker
  - StartSendingPeriodicReportsWorker
  - StartSendingPromptReportsWorker
  - WriteToS3Worker
  - deleting
  - follow
  - unfollow
  - UpdateAudienceInsightWorker
  - rollbar
