:concurrency: 20
:timeout: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - egotter
  - CreateRelationshipWorker
  - CreateTwitterUserWorker
  - ForceUpdateTwitterUserWorker
  - UpdateTwitterUserWorker
