:concurrency: 2
:timeout: 10
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - egotter
  - CreateRelationshipWorker
  - CreateSignedInTwitterUserWorker
  - CreateTwitterUserWorker
  - UpdateTwitterUserWorker
