:concurrency: 5
:timeout: 10
:pidfile: ./tmp/pids/sidekiq_misc.pid
:logfile: ./log/sidekiq_misc.log
:queues:
  - CreateNotificationMessageWorker
  - CreatePromptReportWorker
  - CreateScoreWorker
  - CreateSearchReportWorker
  - CreateTweetsWorker
  - CreateWelcomeMessageWorker
  - DeleteNotFoundUserWorker
  - DeleteForbiddenUserWorker
  - DeleteTweetsWorker
  - FollowEgotterWorker
  - SendMetricsWorker
  - UpdateNotificationMessageWorker
  - UpdatePromptReportWorker
  - UpdateSearchReportWorker
  - UpdateNewsReportWorker
  - UpdateWelcomeMessageWorker

  - CreateForbiddenUserWorker
  - CreateNotFoundUserWorker
  - CreatePollingLogWorker
  - CreateModalOpenLogWorker
  - CreateCrawlerLogWorker
  - CreateSearchLogWorker
  - CreateSearchErrorLogWorker
  - CreateSignInLogWorker
  - ResetTooManyRequestsWorker
  - TweetEgotterWorker
  - UpdateSearchHistoriesWorker
  - UpdateSearchLogWorker
  - UpdateUsageStatWorker
  - rollbar
